#!/usr/bin/env bash

MAX_DESKTOPS=20

WORKSPACES=$(seq -s '\n' 1 1 ${MAX_DESKTOPS})

EMPTY_WORKSPACE=$((hyprctl workspaces | grep ID | awk '{print int($3)}' ; \
            echo -e $WORKSPACES) | sort -n | uniq -u | head -n 1)

hyprctl dispatch workspace ${EMPTY_WORKSPACE}
