theme = "kanagawa"

[editor]
line-number = "relative"
middle-click-paste = false
bufferline = "multiple"
color-modes = true
completion-replace = true
auto-save = true
mouse = false
auto-pairs = false

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false
# git-ignore = false

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal.space]
"H" = ":toggle lsp.display-inlay-hints"

# [keys.normal]
# up = "no_op"
# down = "no_op"
# left = "no_op"
# right = "no_op"
# pageup = "no_op"
# pagedown = "no_op"
# home = "no_op"
# end = "no_op"
