local nnoremap = require("nickd.keymap").nnoremap
local inoremap = require("nickd.keymap").inoremap
local vnoremap = require("nickd.keymap").vnoremap
local xnoremap = require("nickd.keymap").xnoremap

nnoremap("<leader>pv", "<cmd>Ex<CR>")
nnoremap("<C-p>", "<cmd>Files %:p:h:h<CR>")
nnoremap("gd", "<cmd>lua vim.lsp.buf.definition()<CR>")
nnoremap("gD", "<cmd>lua vim.lsp.buf.declaration()<CR>")
nnoremap("gr", "<cmd>lua vim.lsp.buf.references()<CR>")
nnoremap("gi", "<cmd>lua vim.lsp.buf.implementation()<CR>")
nnoremap("K", "<cmd>lua vim.lsp.buf.hover()<CR>")
nnoremap("<C-k>", "<cmd>lua vim.lsp.buf.signature_help()<CR>")
nnoremap("<C-n>", "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>")
nnoremap("<C-N>", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>")
-- Disable arrow keys
--nnoremap("<Left>", "<Nop>")
--nnoremap("<Right>", "<Nop>")
--nnoremap("<Up>", "<Nop>")
--nnoremap("<Down>", "<Nop>")
--vnoremap("<Left>", "<Nop>")
--vnoremap("<Right>", "<Nop>")
--vnoremap("<Up>", "<Nop>")
--vnoremap("<Down>", "<Nop>")
--inoremap("<Left>", "<Nop>")
--inoremap("<Right>", "<Nop>")
--inoremap("<Up>", "<Nop>")
--inoremap("<Down>", "<Nop>")
-- Disable middle click paste
inoremap("<MiddleMouse>", "<Nop>")
inoremap("<2-MiddleMouse>", "<Nop>")
inoremap("<3-MiddleMouse>", "<Nop>")
inoremap("<4-MiddleMouse>", "<Nop>")
nnoremap("<MiddleMouse>", "<Nop>")
nnoremap("<2-MiddleMouse>", "<Nop>")
nnoremap("<3-MiddleMouse>", "<Nop>")
nnoremap("<4-MiddleMouse>", "<Nop>")
vnoremap("<MiddleMouse>", "<Nop>")
vnoremap("<2-MiddleMouse>", "<Nop>")
vnoremap("<3-MiddleMouse>", "<Nop>")
vnoremap("<4-MiddleMouse>", "<Nop>")
xnoremap("<MiddleMouse>", "<Nop>")
xnoremap("<2-MiddleMouse>", "<Nop>")
xnoremap("<3-MiddleMouse>", "<Nop>")
xnoremap("<4-MiddleMouse>", "<Nop>")
